//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lhg.SoccerVirtual.Backend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lhg.SoccerVirtual.Backend.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un alias más corto.
        /// </summary>
        public static string AliasMaxLenghtError {
            get {
                return ResourceManager.GetString("AliasMaxLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un alias más largo.
        /// </summary>
        public static string AliasMinLenghtError {
            get {
                return ResourceManager.GetString("AliasMinLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clásico.
        /// </summary>
        public static string ChampionshipTypeClassicName {
            get {
                return ResourceManager.GetString("ChampionshipTypeClassicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunio.
        /// </summary>
        public static string ChampionshipTypeComunioName {
            get {
                return ResourceManager.GetString("ChampionshipTypeComunioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string ChampionshipTypeSocialName {
            get {
                return ResourceManager.GetString("ChampionshipTypeSocialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenedor de dependencias no ha creado el objeto..
        /// </summary>
        public static string IOCNoCreatedObject {
            get {
                return ResourceManager.GetString("IOCNoCreatedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un apellido más corto.
        /// </summary>
        public static string LastNameMaxLenghtError {
            get {
                return ResourceManager.GetString("LastNameMaxLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un apellido más largo.
        /// </summary>
        public static string LastNameMinLenghtError {
            get {
                return ResourceManager.GetString("LastNameMinLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liga Santander.
        /// </summary>
        public static string LeagueSpanishName {
            get {
                return ResourceManager.GetString("LeagueSpanishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un nombremás corto.
        /// </summary>
        public static string NameMaxLenghtError {
            get {
                return ResourceManager.GetString("NameMaxLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un nombre más largo.
        /// </summary>
        public static string NameMinLenghtError {
            get {
                return ResourceManager.GetString("NameMinLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir una contraseña más corta.
        /// </summary>
        public static string PasswordMaxLenghtError {
            get {
                return ResourceManager.GetString("PasswordMaxLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir una contraseña más larga.
        /// </summary>
        public static string PasswordMinLenghtError {
            get {
                return ResourceManager.GetString("PasswordMinLenghtError", resourceCulture);
            }
        }
    }
}
